---
apiVersion: v1
kind: Secret
metadata:
  name: dharmtest-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-atl/dharmtest-backend-gitops
